version: 2
jobs:
  test-electron:
    machine:
      docker_layer_caching: false
    steps:
    - checkout
    - run: docker pull cypress/included:13.1.0
    - run:
        command: docker-compose run e2e-electron
        no_output_timeout: 3m

  test-chrome:
    machine:
      docker_layer_caching: false
    steps:
    - checkout
    - run: docker pull cypress/included:13.1.0
    - run:
        command: docker-compose run e2e-chrome
        no_output_timeout: 3m

  test-firefox:
    machine:
      docker_layer_caching: false
    steps:
    - checkout
    - run: docker pull cypress/included:13.1.0
    - run:
        command: docker-compose run e2e-firefox
        no_output_timeout: 3m

workflows:
  version: 2
  build:
    jobs:
    - test-electron
    - test-chrome
    - test-firefox
